### PR TITLE
fix: Implement missing "implicit MX" rule

### LINKED ISSUE #126: Implement "implicit MX" rule from RFC5321 section 5.1
Transport mode should use A/AAAA records of the domain from recipient address if (and only if) there are no MX records present.

As described by: https://datatracker.ietf.org/doc/html/rfc5321#section-5.1

### PR DESCRIPTION
**Pull request by j-g00da**
Implements "implicit MX" as described by
https://datatracker.ietf.org/doc/html/rfc5321#section-5.1

Fixes: #126

### CODE REVIEW

File: src/transport.rs [hunk 1]
```diff
@@ -59,25 +59,33 @@ impl TransportHandler {
...
-                let mx_records = dns_resolver.mx_lookup(query).await.map_err(|e| {
-                    if e.is_no_records_found() {
-                        format!("512 No MX records for {mx_domain}")
-                    } else if e.is_nx_domain() {
-                        format!("512 Domain {mx_domain} does not exist")
-                    } else {
-                        format!("421 DNS resolution failed for {mx_domain}")
+
+                match dns_resolver.mx_lookup(query).await {
+                    Ok(mx_records) => {
```
Comment (link2xt) [inline src/transport.rs:64]: There is also a case of [null MX](https://www.rfc-editor.org/rfc/rfc7505), a single entry with 0 preference and "." as the domain, in this case no message should be sent.

Comment (j-g00da) [reply src/transport.rs:64]: I can make it more explicit, but in such case message won't be sent anyway as this will result in `vec![(0, "".to_string())]`, which will fail DNS resolution when getting socket addresses.

Comment (link2xt) [reply src/transport.rs:64]: I think null MX is better be explicit case to not even call the resolver.

Comment (j-g00da) [reply src/transport.rs:64]: Added: https://github.com/chatmail/filtermail/pull/127/commits/f53dae4145748aae91b2559d1824f37fc2a9534a

**Review by link2xt — APPROVED** [review]
